### ISSUE TITLE
Selenium: NoSuchElementException - Lecture element not found using XPath

### ISSUE THREAD

**Issue by Issa-db** [SkyNickYT/365datascience_downloader#2] opened 2024-11-13 19:17 UTC
<img width="1197" alt="Screenshot 2024-11-13 at 9 17 02 PM" src="https://github.com/user-attachments/assets/f443f276-252e-4501-b6cc-76801d13c63b">

**Comment by SkyNickYT** [comment] 2024-11-14 04:15
Can you tell me the URL you used to fetch the course?

Also, at line 427 of `main.py` try changing the `time.sleep(2)` value in brackets to something higher for once, say `time.sleep(20)` If that makes a difference.

**Comment by Issa-db** [comment] 2024-11-14 07:50
I try to add more time for time.sleep(20) but still with same error
the command line i use with : python3 main.py --course https://learn.365datascience.com/courses/preview/introduction-to-data-and-data-science/ 
<img width="1234" alt="Screenshot 2024-11-14 at 9 48 56 AM" src="https://github.com/user-attachments/assets/b3e4a2c1-cea3-4f5e-8be4-ed837e854329">

**Comment by SkyNickYT** [comment] 2024-11-14 08:06
> I try to add more time for time.sleep(20) but still with same error
> the command line i use with : python3 main.py --course https://learn.365datascience.com/courses/preview/introduction-to-data-and-data-science/ 
> <img width="1234" alt="Screenshot 2024-11-14 at 9 48 56 AM" src="https://github.com/user-attachments/assets/b3e4a2c1-cea3-4f5e-8be4-ed837e854329">
> 

You're using a preview link it makes sense you're getting the error that's why, kindly navigate to the first lecture of the course (then use that link instead). You can switch the `time.sleep()` function back to its original value, the script should work then as intended.

Please report again after trying.

**Comment by Issa-db** [comment] 2024-11-14 08:17
Party Begin 🥂
<img width="1216" alt="Screenshot 2024-11-14 at 10 15 35 AM" src="https://github.com/user-attachments/assets/64e5b327-52f5-430e-a528-617623355602">

**Comment by SkyNickYT** [comment] 2024-11-14 08:23
> Party Begin 🥂 <img alt="Screenshot 2024-11-14 at 10 15 35 AM" width="1216" src="https://private-user-images.githubusercontent.com/83542891/386102232-64e5b327-52f5-430e-a528-617623355602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzI1NTQsIm5iZiI6MTczMTU3MjI1NCwicGF0aCI6Ii84MzU0Mjg5MS8zODYxMDIyMzItNjRlNWIzMjctNTJmNS00MzBlLWE1MjgtNjE3NjIzMzU1NjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDA4MTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMjU5ODY5M2MzYWY4MzFjMjAzYWQwMTkxNjk0MzhmODdlMTM3YWEzYWM0MmRiMzVmNjE0YzhhMTE5ZDdiM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A4zR4QwBwVioNBkOqlA6O1HcSnrh27FBbnzCFRZnxK0">

That's sweet! Enjoy, and Happy downloading! 🔥 (feel free to open more issues if need be - and if you own a subscription and can help in this tool's improvement beyond the promotional period please open an enhancement request, it will be very valuable)

(Closing comment above, issue has now been closed.)
`STATUS: RESOLVED`

**Closed as completed by SkyNickYT** 2024-11-14 08:23 UTC
Labels: user-error
